class_name TestTruco
extends RefCounted
func run(t:TestHelpers)->void:
	var rules: TrucoRules=TrucoRules.new();var four: Dictionary=CardData.make(1,"truco","4","clubs");var three: Dictionary=CardData.make(2,"truco","3","diamonds")
	t.equal(rules.compare_truco_cards(three,four,"5"),1,"ordem normal");t.equal(rules.compare_truco_cards(four,four,"5"),0,"empate")
	var clubs: Dictionary=CardData.make(3,"truco","5","clubs");var diamonds: Dictionary=CardData.make(4,"truco","5","diamonds");t.equal(rules.compare_truco_cards(clubs,diamonds,"5"),1,"força manilha")
	t.equal(rules.hand_result([0,0]),0,"duas vazas");t.equal(rules.hand_result([-1,1]),1,"empate primeira")
	var rng: RandomNumberGenerator=RandomNumberGenerator.new();rng.seed=4;var state: Dictionary=rules.create_initial_state([1,2,3,4],rng);t.equal(rules.validate_invariants(state),"OK","conservação Truco 2x2")
	t.equal(rules.next_raise_value(1), 3, "progressão 1 para 3")
	t.equal(rules.next_raise_value(3), 6, "progressão 3 para 6")
	t.equal(rules.next_raise_value(6), 9, "progressão 6 para 9")
	t.equal(rules.next_raise_value(9), 12, "progressão 9 para 12")
	t.equal(rules.next_raise_value(12), 0, "não aumenta acima de 12")
	var duel: Dictionary = rules.create_initial_state([1,2], rng)
	rules.apply_action(duel, 1, {"type":"REQUEST_TRUCO"}, rng)
	t.equal(duel.target_value, 3, "pedido de Truco vale três")
	t.check(not rules.validate_action(duel, 1, {"type":"ACCEPT"}).accepted, "equipe incorreta não responde")
	rules.apply_action(duel, 2, {"type":"RAISE"}, rng)
	t.equal(duel.target_value, 6, "resposta pode pedir seis")
	t.equal(duel.responding_team, 0, "responsabilidade troca de equipe")
	rules.apply_action(duel, 1, {"type":"RUN"}, rng)
	t.equal(duel.scores[1], 1, "correr concede apenas valor aceito")
	var reveal: Dictionary = rules.create_initial_state([1,2], rng)
	var first_uid: int = int(reveal.hands[1][0].uid)
	var second_uid: int = int(reveal.hands[2][0].uid)
	rules.apply_action(reveal, 1, {"type":"PLAY_CARD","card_uid":first_uid}, rng)
	rules.apply_action(reveal, 2, {"type":"PLAY_CARD","card_uid":second_uid}, rng)
	t.equal(reveal.phase, TrucoRules.Phase.TRICK_REVEAL, "última carta entra em revelação")
	t.equal(reveal.played.size(), 2, "cartas permanecem abertas na revelação")
	t.equal(reveal.trick_history.size(), 0, "próxima vaza não começa antes da transição")
	t.check(rules.advance_reveal(reveal, rng), "transição autoritativa avança revelação")
	t.equal(reveal.trick_history.size(), 1, "histórico registra a vaza uma vez")
	t.equal(reveal.trick_history[0].plays[0].peer_id, 1, "histórico preserva ordem e jogador")
	t.check(not rules.advance_reveal(reveal, rng), "transição antiga não avança estado novo")
